In [1]:
import pandas as pd
energia = pd.read_csv('Energía_electrica.csv', sep=',', index_col=0, skiprows=4).drop(["Indicator Name", "Indicator Code", "Country Code", "Unnamed: 64"], axis=1)

display(energia)

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afganistán,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,206.454411,207.013343,219.253430,280.214547,312.228825,NaN,NaN,NaN,NaN,NaN
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1943.343354,2205.703920,2118.327776,2533.252829,2309.366503,NaN,NaN,NaN,NaN,NaN
Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2649.689133,2946.957007,2859.821173,2917.304002,2818.337231,NaN,NaN,NaN,NaN,NaN
"Yemen, Rep. del",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,254.849361,193.803757,193.804009,250.963242,219.799922,NaN,NaN,NaN,NaN,NaN
Sudáfrica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4542.596473,4566.287489,4365.919260,4285.477260,4197.907047,NaN,NaN,NaN,NaN,NaN
Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,590.548982,631.739148,733.211979,747.060397,717.349168,NaN,NaN,NaN,NaN,NaN
Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,606.644199,636.249337,608.762505,628.747278,609.125952,NaN,NaN,NaN,NaN,NaN

In [2]:
new_energia = energia.T

print(new_energia.index)

del_year = []
for x in new_energia.index:
    if(int(x) < 1998 or int(x) > 2014):
        del_year.append(x)
new_energia = new_energia.drop(del_year)

#petro = petro.loc[petro["Country Name"] >= 1990]

display(new_energia)

Index(['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019'],
      dtype='object')

Country Name,Aruba,Afganistán,Angola,Albania,Andorra,El mundo árabe,Emiratos Árabes Unidos,Argentina,Armenia,Samoa Americana,...,Islas Vírgenes (EE.UU.),Viet Nam,Vanuatu,Mundo,Samoa,Kosovo,"Yemen, Rep. del",Sudáfrica,Zambia,Zimbabwe
1998,NaN,NaN,73.309196,734.849914,NaN,1433.163852,11232.348481,1967.254444,1308.591055,NaN,...,NaN,232.962102,NaN,2284.621224,NaN,NaN,133.857660,4606.904496,582.578826,876.303474
1999,NaN,NaN,71.910848,1414.703784,NaN,1484.222672,12219.010301,2033.771811,1307.533582,NaN,...,NaN,253.302706,NaN,2317.249697,NaN,NaN,132.319620,4470.963333,585.667795,926.859549
2000,NaN,NaN,75.264678,1449.647413,NaN,1517.005675,12314.051222,2088.808140,1297.567005,NaN,...,NaN,286.620972,NaN,2386.742882,NaN,1557.058824,142.741669,4579.953241,597.545455,897.868169
2001,NaN,NaN,82.616571,1351.230796,NaN,1580.093902,12133.638980,2120.579943,1269.222310,NaN,...,NaN,326.531880,NaN,2380.366325,NaN,1968.075789,147.390614,4302.118040,618.675701,872.029101
2002,NaN,NaN,86.018844,1578.165919,NaN,1648.292830,12502.669760,2014.476557,1236.330652,NaN,...,NaN,377.558397,NaN,2435.125561,NaN,1953.815697,155.283452,4528.816147,644.111787,878.345765
2003,NaN,NaN,95.853103,1469.264539,NaN,1718.913222,12366.067051,2180.326817,1320.440620,NaN,...,NaN,433.199060,NaN,2500.520170,NaN,1908.461924,165.657098,4559.774530,663.424580,879.636368
2004,NaN,NaN,87.535308,1797.525487,NaN,1765.840771,11958.992963,2293.309369,1440.320990,NaN,...,NaN,483.959003,NaN,2578.400172,NaN,2111.318521,173.387053,4589.905059,685.156721,855.746698
2005,NaN,NaN,109.295230,1722.072850,NaN,1840.432063,12279.912166,2408.432525,1521.499737,NaN,...,NaN,569.956857,NaN,2656.210671,NaN,2169.095663,183.663644,4636.930100,692.714988,891.882790
2006,NaN,NaN,144.715351,1218.360146,NaN,1940.406475,11693.389689,2374.097471,1639.789244,NaN,...,NaN,645.209019,NaN,2732.503544,NaN,2225.018842,193.883828,4721.933482,704.562380,871.951614
2007,NaN,NaN,133.267239,1213.124369,NaN,1995.377548,11451.913634,2455.656576,1773.159682,NaN,...,NaN,728.088244,NaN,2822.175780,NaN,2395.863861,211.206241,4851.693185,664.162833,760.203924
2008,NaN,NaN,172.384914,1617.744156,NaN,2061.822740,11294.188141,2772.843222,1669.407742,NaN,...,NaN,802.554045,NaN,2843.484276,NaN,2644.526129,230.128193,4665.176133,589.561607,627.890402
2009,NaN,NaN,189.257654,1835.684072,NaN,2119.801726,10618.801289,2730.123232,1661.304418,NaN,...,NaN,906.154086,NaN,2794.003129,NaN,2558.084877,226.989500,4428.154433,568.438970,585.456912
2010,NaN,NaN,206.454411,1943.343354,NaN,2296.780903,10609.956412,2877.652653,1726.259758,NaN,...,NaN,1022.432667,NaN,2958.107370,NaN,2649.689133,254.849361,4542.596473,590.548982,606.644199
2011,NaN,NaN,207.013343,2205.703920,NaN,2332.708771,10287.056445,2929.075029,1807.033316,NaN,...,NaN,1102.804979,NaN,3023.382626,NaN,2946.957007,193.803757,4566.287489,631.739148,636.249337
2012,NaN,NaN,219.253430,2118.327776,NaN,2371.597009,10416.014884,3000.603523,1892.013429,NaN,...,NaN,1206.302894,NaN,3050.432295,NaN,2859.821173,193.804009,4365.919260,733.211979,608.762505
2013,NaN,NaN,280.214547,2533.252829,NaN,2427.835381,10724.501544,2967.376558,1931.264115,NaN,...,NaN,1276.843711,NaN,3110.752785,NaN,2917.304002,250.963242,4285.477260,747.060397,628.747278
2014,NaN,NaN,312.228825,2309.366503,NaN,2501.479664,11088.350286,3074.702071,1961.610395,NaN,...,NaN,1423.688345,NaN,3132.786963,NaN,2818.337231,219.799922,4197.907047,717.349168,609.125952

In [3]:
import numpy as np

nan_cols = new_energia.isna().sum()

n_years = len(new_energia.index)
cols = new_energia.columns
print(nan_cols)

del_cols = []

p30 = nan_cols.max()*3/10

for x in range(len(cols)):
    if(nan_cols[x] > p30):
        #rint(nan_cols[x])
        del_cols.append(cols[x])
    new_energia = new_energia.replace({cols[x] : {np.nan: new_energia[cols[x]].mean()}})
display(del_cols)
new_energia = new_energia.drop(del_cols, axis=1)
display(new_energia)

Country Name
Aruba              17
Afganistán         17
Angola              0
Albania             0
Andorra            17
                   ..
Kosovo              2
Yemen, Rep. del     0
Sudáfrica           0
Zambia              0
Zimbabwe            0
Length: 264, dtype: int64

['Aruba',
 'Afganistán',
 'Andorra',
 'Samoa Americana',
 'Antigua y Barbuda',
 'Burundi',
 'Burkina Faso',
 'Bahamas',
 'Belice',
 'Bermudas',
 'Barbados',
 'Bhután',
 'República Centroafricana',
 'Islas del Canal',
 'Comoras',
 'Cabo Verde',
 'Islas Caimán',
 'Djibouti',
 'Dominica',
 'Fiji',
 'Islas Feroe',
 'Micronesia (Estados Federados de)',
 'Guinea',
 'Gambia',
 'Guinea-Bissau',
 'Guinea Ecuatorial',
 'Granada',
 'Groenlandia',
 'Guam',
 'Guyana',
 'Isla de Man',
 'No clasificado',
 'Kiribati',
 'Saint Kitts y Nevis',
 'República Democrática Popular Lao',
 'Liberia',
 'Santa Lucía',
 'Países de ingreso bajo',
 'Liechtenstein',
 'Lesotho',
 'Región Administrativa Especial de Macao, China',
 'Isla de San Martín (parte francesa)',
 'Mónaco',
 'Madagascar',
 'Maldivas',
 'Islas Marshall',
 'Malí',
 'Montenegro',
 'Mariana',
 'Mauritania',
 'Malawi',
 'Nueva Caledonia',
 'Nauru',
 'Otros Estados pequeos',
 'Palau',
 'Papua Nueva Guinea',
 'Puerto Rico',
 'Ribera Occidental y Gaza',
 'Estados pequeos de las Islas del Pacfico',
 'Polinesia Francesa',
 'Rwanda',
 'Islas Salomón',
 'Sierra Leona',
 'San Marino',
 'Somalia',
 'Sudán del Sur',
 'Pequeños Estados',
 'Santo Tomé y Príncipe',
 'Eswatini',
 'Sint Maarten (Dutch part)',
 'Seychelles',
 'Islas Turcas y Caicos',
 'Chad',
 'Timor-Leste',
 'Tonga',
 'Tuvalu',
 'Uganda',
 'San Vicente y las Granadinas',
 'Islas Vírgenes Británicas',
 'Islas Vírgenes (EE.UU.)',
 'Vanuatu',
 'Samoa']

Country Name,Angola,Albania,El mundo árabe,Emiratos Árabes Unidos,Argentina,Armenia,Australia,Austria,Azerbaiyán,Bélgica,...,Estados Unidos,Uzbekistán,Venezuela,Viet Nam,Mundo,Kosovo,"Yemen, Rep. del",Sudáfrica,Zambia,Zimbabwe
1998,73.309196,734.849914,1433.163852,11232.348481,1967.254444,1308.591055,9783.442895,6706.708677,1936.939214,7913.058580,...,13154.763027,1779.884412,2670.151753,232.962102,2284.621224,2378.895245,133.857660,4606.904496,582.578826,876.303474
1999,71.910848,1414.703784,1484.222672,12219.010301,2033.771811,1307.533582,10036.457783,6972.189816,2022.485985,7944.129807,...,13281.869983,1745.953072,2602.249948,253.302706,2317.249697,2378.895245,132.319620,4470.963333,585.667795,926.859549
2000,75.264678,1449.647413,1517.005675,12314.051222,2088.808140,1297.567005,10193.912181,7076.269483,2040.479090,8247.677113,...,13671.052024,1780.457924,2667.609551,286.620972,2386.742882,1557.058824,142.741669,4579.953241,597.545455,897.868169
2001,82.616571,1351.230796,1580.093902,12133.638980,2120.579943,1269.222310,10636.377685,7333.231953,2106.470066,8267.187216,...,13046.614148,1769.396081,2732.399185,326.531880,2380.366325,1968.075789,147.390614,4302.118040,618.675701,872.029101
2002,86.018844,1578.165919,1648.292830,12502.669760,2014.476557,1236.330652,10813.122729,7427.656445,1996.708252,8311.892679,...,13296.182299,1775.809844,2758.560737,377.558397,2435.125561,1953.815697,155.283452,4528.816147,644.111787,878.345765
2003,95.853103,1469.264539,1718.913222,12366.067051,2180.326817,1320.440620,10434.874393,7695.080037,2235.459856,8411.900657,...,13307.492009,1764.456256,2664.722994,433.199060,2500.520170,1908.461924,165.657098,4559.774530,663.424580,879.636368
2004,87.535308,1797.525487,1765.840771,11958.992963,2293.309369,1440.320990,10554.815823,7808.157792,2281.947872,8576.223497,...,13388.589711,1765.480285,2796.712523,483.959003,2578.400172,2111.318521,173.387053,4589.905059,685.156721,855.746698
2005,109.295230,1722.072850,1840.432063,12279.912166,2408.432525,1521.499737,10458.450193,7977.681597,2388.388734,8509.997073,...,13704.577048,1717.201055,2886.490229,569.956857,2656.210671,2169.095663,183.663644,4636.930100,692.714988,891.882790
2006,144.715351,1218.360146,1940.406475,11693.389689,2374.097471,1639.789244,10490.484542,8244.401952,2552.286214,8683.671285,...,13583.266959,1755.759629,2999.307938,645.209019,2732.503544,2225.018842,193.883828,4721.933482,704.562380,871.951614
2007,133.267239,1213.124369,1995.377548,11451.913634,2455.656576,1773.159682,10972.891740,8207.474739,2118.210528,8614.679503,...,13657.452828,1664.061337,3019.163883,728.088244,2822.175780,2395.863861,211.206241,4851.693185,664.162833,760.203924
2008,172.384914,1617.744156,2061.822740,11294.188141,2772.843222,1669.407742,10749.110555,8233.014833,2040.760435,8521.496740,...,13663.427968,1652.651010,3125.254199,802.554045,2843.484276,2644.526129,230.128193,4665.176133,589.561607,627.890402
2009,189.257654,1835.684072,2119.801726,10618.801289,2730.123232,1661.304418,10791.593098,7944.796096,1620.387420,7903.955479,...,12913.714688,1643.149881,3090.969719,906.154086,2794.003129,2558.084877,226.989500,4428.154433,568.438970,585.456912
2010,206.454411,1943.343354,2296.780903,10609.956412,2877.652653,1726.259758,10726.928183,8382.711154,1603.431374,8393.949623,...,13395.139932,1653.467496,3195.681847,1022.432667,2958.107370,2649.689133,254.849361,4542.596473,590.548982,606.644199
2011,207.013343,2205.703920,2332.708771,10287.056445,2929.075029,1807.033316,10627.293865,8425.167753,1705.424633,8028.798731,...,13247.013128,1631.526207,3256.570144,1102.804979,3023.382626,2946.957007,193.803757,4566.287489,631.739148,636.249337
2012,219.253430,2118.327776,2371.597009,10416.014884,3000.603523,1892.013429,10407.740307,8548.882199,2052.650965,7988.524644,...,12966.115934,1610.807906,3304.220299,1206.302894,3050.432295,2859.821173,193.804009,4365.919260,733.211979,608.762505
2013,280.214547,2533.252829,2427.835381,10724.501544,2967.376558,1931.264115,10220.887301,8509.611580,2092.536521,7989.671853,...,13006.749201,1637.194477,3298.731371,1276.843711,3110.752785,2917.304002,250.963242,4285.477260,747.060397,628.747278
2014,312.228825,2309.366503,2501.479664,11088.350286,3074.702071,1961.610395,10071.398979,8355.841952,2202.393918,7709.123078,...,12997.448629,1645.441629,2718.942775,1423.688345,3132.786963,2818.337231,219.799922,4197.907047,717.349168,609.125952

In [4]:
new_energia = new_energia.sum(axis=1)
new_energia = new_energia.to_frame("kWh per cápita")
display(new_energia)

      kWh per cápita
1998   582275.856940
1999   591871.103193
2000   605625.875204
2001   614291.725746
2002   626224.360133
2003   639813.251571
2004   651625.392027
2005   663109.736623
2006   678377.956881
2007   691299.550660
2008   703205.749631
2009   684756.815589
2010   713413.061962
2011   713350.977497
2012   716736.704749
2013   720612.963709
2014   720677.860713

In [5]:
data = pd.read_csv('p_g_a.csv', sep=',', index_col=0)

years = new_energia.index

new_data = pd.concat([data.reset_index(), new_energia.reset_index()], axis=1)
new_data = new_data.set_index(years).drop(["index"], axis=1)
display(new_data)

,Tierras de cultivo[Kha],Tierras agrícolas[Kha],Tierras arables[Kha],Tierr. dedicadas a praderas y pastizales perman.[Kha],Tierras destinadas a cultivos permanentes[Kha],Tierras en barbecho[Kha],Tierras destinadas a cultivos temporales[Kha],Tierr. destinadas a praderas y pastizales tempor.[Kha],Praderas y pastizales permanentes naturales[Kha],Praderas y pastizales permanentes cultivados[Kha],Tierr. agrícolas bajo cubiertas protectoras[Kha],Chickens[Heads],Cattle[Heads],Goats[Heads],Sheep[Heads],Buffaloes[Heads],Pigs[Heads],kg eq de petróleo per cápita,kWh per cápita
1998,1.598180e+06,5.281621e+06,1.459381e+06,3.683441e+06,138799.2000,8863.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.626209e+10,1.412693e+09,8.561212e+08,1.172186e+09,183211316.0,1.278714e+09,409278.121679,582275.856940
1999,1.601388e+06,5.284178e+06,1.459728e+06,3.682790e+06,141660.3000,8698.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.706533e+10,1.418447e+09,8.819086e+08,1.189076e+09,184943049.0,1.319562e+09,406421.106346,591871.103193
2000,1.598015e+06,5.288636e+06,1.454432e+06,3.690621e+06,143583.5500,9084.9500,0.0000,0.0000,0.0000,0.0000,0.0000,1.801444e+10,1.424550e+09,9.072522e+08,1.197473e+09,186849897.0,1.337635e+09,407955.619866,605625.875204
2001,1.592676e+06,5.281914e+06,1.446734e+06,3.689238e+06,145941.7800,113717.2000,190502.3200,19155.2100,463125.0000,143624.2000,0.0000,1.872377e+10,1.421927e+09,9.213028e+08,1.174409e+09,189045179.0,1.306011e+09,417434.985213,614291.725746
2002,1.587330e+06,5.266591e+06,1.439858e+06,3.679261e+06,147471.4700,134021.7300,346964.5200,48466.7000,568089.9000,160455.3000,0.0000,2.021781e+10,1.428530e+09,9.297619e+08,1.166830e+09,191434819.0,1.319323e+09,420252.145081,626224.360133
2003,1.588052e+06,5.246291e+06,1.437800e+06,3.658239e+06,150252.1500,143935.0490,398502.5850,49258.8560,464821.1000,155784.1000,0.0000,2.015931e+10,1.439226e+09,9.487161e+08,1.179128e+09,194243011.0,1.323360e+09,429199.031721,639813.251571
2004,1.595130e+06,5.210371e+06,1.441324e+06,3.615241e+06,153806.4300,132530.5700,401949.9700,47341.4600,472733.6000,188660.9000,0.0000,2.095678e+10,1.452483e+09,9.751360e+08,1.217176e+09,196301811.0,1.313687e+09,437615.378156,651625.392027
2005,1.600839e+06,5.220849e+06,1.444260e+06,3.620010e+06,156578.5600,132258.3200,409327.0400,46301.8800,454603.9000,191006.5000,0.0000,2.166824e+10,1.465399e+09,1.003008e+09,1.256596e+09,199371789.0,1.332702e+09,436683.447635,663109.736623
2006,1.591868e+06,5.214316e+06,1.432412e+06,3.622448e+06,159457.1313,118769.5000,405984.2300,44875.4600,464610.5000,193248.1000,0.0000,2.204406e+10,1.479334e+09,9.990491e+08,1.260618e+09,203106269.0,1.365627e+09,447577.943811,678377.956881
2007,1.594217e+06,5.209112e+06,1.430834e+06,3.614895e+06,163383.3000,118194.2000,411256.9500,43159.7800,491530.9000,202956.0000,0.0000,2.301207e+10,1.484982e+09,1.018802e+09,1.266893e+09,206789865.0,1.345023e+09,451843.346378,691299.550660
2008,1.595744e+06,5.199566e+06,1.430409e+06,3.603822e+06,165335.1700,113878.8600,427827.6400,43204.5400,532953.3000,309091.6000,0.0000,2.400005e+10,1.498367e+09,1.045958e+09,1.249078e+09,209013157.0,1.385392e+09,454571.909766,703205.749631
2009,1.597507e+06,5.192755e+06,1.429397e+06,3.595247e+06,168110.3900,109485.2300,420351.3800,41678.4800,532177.9500,308910.3200,0.0000,2.494299e+10,1.480590e+09,1.062329e+09,1.245239e+09,224246978.0,1.446399e+09,438522.543106,684756.815589
2010,1.600852e+06,5.197341e+06,1.429282e+06,3.596489e+06,171570.6400,111851.6000,498519.0800,40378.8100,912919.5000,329250.4900,0.0000,2.554736e+10,1.480624e+09,1.060347e+09,1.244369e+09,223498447.0,1.445905e+09,450989.055294,713413.061962
2011,1.612221e+06,5.220308e+06,1.437617e+06,3.608087e+06,174604.1200,108320.4400,512821.2800,39321.2700,914725.9700,327467.5100,0.0000,2.466127e+10,1.481816e+09,1.073541e+09,1.264569e+09,223337483.0,1.450940e+09,451187.835339,713350.977497
2012,1.622262e+06,5.221104e+06,1.445300e+06,3.598842e+06,176962.1000,110812.6800,500146.3800,37267.7200,930492.0900,329314.2900,230.0000,2.540633e+10,1.491532e+09,1.091212e+09,1.279543e+09,223825531.0,1.470606e+09,450883.212472,716736.704749
2013,1.625059e+06,5.209852e+06,1.446902e+06,3.584792e+06,178157.5843,108597.1260,511357.3682,37471.7183,909137.8261,335816.5644,1026.0255,2.578876e+10,1.495101e+09,1.106942e+09,1.310763e+09,223737572.0,1.464392e+09,446222.795232,720612.963709
2014,1.626226e+06,5.208838e+06,1.447809e+06,3.582609e+06,178417.2706,98812.7064,513339.7562,37811.7900,826081.8824,189475.7473,1141.8608,2.575145e+10,1.502947e+09,1.121308e+09,1.305057e+09,225030802.0,1.474566e+09,445731.976025,720677.860713

In [7]:
new_data.to_csv('p_g_a_e.csv', index=True)