In [1]:
import pandas as pd
pob = pd.read_csv('world-population.csv', sep=',', index_col=0).drop(["Code"], axis=1)

display(pob)

             Year  Population
Entity
Afghanistan  1800     3280000
Afghanistan  1801     3280000
Afghanistan  1802     3280000
Afghanistan  1803     3280000
Afghanistan  1804     3280000
...           ...         ...
Zimbabwe     2015    13815000
Zimbabwe     2016    14030000
Zimbabwe     2017    14237000
Zimbabwe     2018    14439000
Zimbabwe     2019    14645000

[46883 rows x 2 columns]

In [2]:
import numpy as np

years = pob["Year"].drop_duplicates().values
n_years = len(years)
cols = pob.index.to_series().drop_duplicates().values

new_years = []

for x in years:
    try:
        if int(x) <= 2014 and int(x) >= 1998:
            new_years.append(x)
    except:
        print("Skip") 
print(cols)
print(new_years)

Skip
Skip
Skip
Skip
Skip
Skip
Skip
Skip
Skip
Skip
['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bonaire Sint Eustatius and Saba'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Channel Islands' 'Chile' 'China' 'Colombia' 'Comoros' 'Congo'
 'Cook Islands' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao'
 'Cyprus' 'Czech Republic' 'Democratic Republic of Congo' 'Denmark'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Ethiopia' 'Europe'
 'Faeroe Islands' 'Falkland Islands' 'Fiji' 'Finland' 'France'
 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia' 'Germany'
 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras'
 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Isle of Man' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan'
 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait' 'Kyrgyzstan' 'Laos'
 'Latin America' 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Libya'
 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Macao' 'Macedonia' 'Madagascar'
 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands'
 'Martinique' 'Mauritania' 'Mauritius' 'Mayotte' 'Mexico'
 'Micronesia (country)' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro'
 'Montserrat' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal'
 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria'
 'Niue' 'North America' 'North Korea' 'Northern Mariana Islands' 'Norway'
 'Oceania' 'Oman' 'Pakistan' 'Palau' 'Palestine' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Puerto Rico' 'Qatar' 'Reunion' 'Romania' 'Russia' 'Rwanda'
 'Saint Barthlemy' 'Saint Helena' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Sint Maarten (Dutch part)' 'Slovakia'
 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa' 'South Korea'
 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Swaziland' 'Sweden'
 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor'
 'Togo' 'Tokelau' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey'
 'Turkmenistan' 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Vatican'
 'Venezuela' 'Vietnam' 'Wallis and Futuna' 'Western Sahara' 'World'
 'Yemen' 'Zambia' 'Zimbabwe']
['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014']

In [3]:
year_col = "Year"

new_pob = pob.loc[pob[year_col].isin(new_years)].loc["World",:].set_index([new_years]).drop([year_col], axis=1)

display(new_pob)

      Population
1998  5984794112
1999  6064239104
2000  6143494144
2001  6222626816
2002  6301772800
2003  6381185024
2004  6461158912
2005  6541906944
2006  6623518208
2007  6705947136
2008  6789088768
2009  6872766976
2010  6956824064
2011  7041193984
2012  7125828096
2013  7210582016
2014  7295290880

In [8]:
data = pd.read_csv('p_g_a_e.csv', sep=',', index_col=0)

years = new_pob.index

new_data = pd.concat([data.reset_index(), new_pob.reset_index()], axis=1)
new_data = new_data.set_index(years).drop(["index"], axis=1)

display(new_data)

,Tierras de cultivo[Kha],Tierras agrÃ­colas[Kha],Tierras arables[Kha],Tierr. dedicadas a praderas y pastizales perman.[Kha],Tierras destinadas a cultivos permanentes[Kha],Tierras en barbecho[Kha],Tierras destinadas a cultivos temporales[Kha],Tierr. destinadas a praderas y pastizales tempor.[Kha],Praderas y pastizales permanentes naturales[Kha],Praderas y pastizales permanentes cultivados[Kha],Tierr. agrÃ­colas bajo cubiertas protectoras[Kha],Chickens[Heads],Cattle[Heads],Goats[Heads],Sheep[Heads],Buffaloes[Heads],Pigs[Heads],kg eq de petrÃ³leo per cÃ¡pita,kWh per cÃ¡pita,Population
1998,1.598180e+06,5.281621e+06,1.459381e+06,3.683441e+06,138799.2000,8863.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.626209e+10,1.412693e+09,8.561212e+08,1.172186e+09,183211316.0,1.278714e+09,409278.121679,582275.856940,5984794112
1999,1.601388e+06,5.284178e+06,1.459728e+06,3.682790e+06,141660.3000,8698.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.706533e+10,1.418447e+09,8.819086e+08,1.189076e+09,184943049.0,1.319562e+09,406421.106346,591871.103193,6064239104
2000,1.598015e+06,5.288636e+06,1.454432e+06,3.690621e+06,143583.5500,9084.9500,0.0000,0.0000,0.0000,0.0000,0.0000,1.801444e+10,1.424550e+09,9.072522e+08,1.197473e+09,186849897.0,1.337635e+09,407955.619866,605625.875204,6143494144
2001,1.592676e+06,5.281914e+06,1.446734e+06,3.689238e+06,145941.7800,113717.2000,190502.3200,19155.2100,463125.0000,143624.2000,0.0000,1.872377e+10,1.421927e+09,9.213028e+08,1.174409e+09,189045179.0,1.306011e+09,417434.985213,614291.725746,6222626816
2002,1.587330e+06,5.266591e+06,1.439858e+06,3.679261e+06,147471.4700,134021.7300,346964.5200,48466.7000,568089.9000,160455.3000,0.0000,2.021781e+10,1.428530e+09,9.297619e+08,1.166830e+09,191434819.0,1.319323e+09,420252.145081,626224.360133,6301772800
2003,1.588052e+06,5.246291e+06,1.437800e+06,3.658239e+06,150252.1500,143935.0490,398502.5850,49258.8560,464821.1000,155784.1000,0.0000,2.015931e+10,1.439226e+09,9.487161e+08,1.179128e+09,194243011.0,1.323360e+09,429199.031721,639813.251571,6381185024
2004,1.595130e+06,5.210371e+06,1.441324e+06,3.615241e+06,153806.4300,132530.5700,401949.9700,47341.4600,472733.6000,188660.9000,0.0000,2.095678e+10,1.452483e+09,9.751360e+08,1.217176e+09,196301811.0,1.313687e+09,437615.378156,651625.392027,6461158912
2005,1.600839e+06,5.220849e+06,1.444260e+06,3.620010e+06,156578.5600,132258.3200,409327.0400,46301.8800,454603.9000,191006.5000,0.0000,2.166824e+10,1.465399e+09,1.003008e+09,1.256596e+09,199371789.0,1.332702e+09,436683.447635,663109.736623,6541906944
2006,1.591868e+06,5.214316e+06,1.432412e+06,3.622448e+06,159457.1313,118769.5000,405984.2300,44875.4600,464610.5000,193248.1000,0.0000,2.204406e+10,1.479334e+09,9.990491e+08,1.260618e+09,203106269.0,1.365627e+09,447577.943811,678377.956881,6623518208
2007,1.594217e+06,5.209112e+06,1.430834e+06,3.614895e+06,163383.3000,118194.2000,411256.9500,43159.7800,491530.9000,202956.0000,0.0000,2.301207e+10,1.484982e+09,1.018802e+09,1.266893e+09,206789865.0,1.345023e+09,451843.346378,691299.550660,6705947136
2008,1.595744e+06,5.199566e+06,1.430409e+06,3.603822e+06,165335.1700,113878.8600,427827.6400,43204.5400,532953.3000,309091.6000,0.0000,2.400005e+10,1.498367e+09,1.045958e+09,1.249078e+09,209013157.0,1.385392e+09,454571.909766,703205.749631,6789088768
2009,1.597507e+06,5.192755e+06,1.429397e+06,3.595247e+06,168110.3900,109485.2300,420351.3800,41678.4800,532177.9500,308910.3200,0.0000,2.494299e+10,1.480590e+09,1.062329e+09,1.245239e+09,224246978.0,1.446399e+09,438522.543106,684756.815589,6872766976
2010,1.600852e+06,5.197341e+06,1.429282e+06,3.596489e+06,171570.6400,111851.6000,498519.0800,40378.8100,912919.5000,329250.4900,0.0000,2.554736e+10,1.480624e+09,1.060347e+09,1.244369e+09,223498447.0,1.445905e+09,450989.055294,713413.061962,6956824064
2011,1.612221e+06,5.220308e+06,1.437617e+06,3.608087e+06,174604.1200,108320.4400,512821.2800,39321.2700,914725.9700,327467.5100,0.0000,2.466127e+10,1.481816e+09,1.073541e+09,1.264569e+09,223337483.0,1.450940e+09,451187.835339,713350.977497,7041193984
2012,1.622262e+06,5.221104e+06,1.445300e+06,3.598842e+06,176962.1000,110812.6800,500146.3800,37267.7200,930492.0900,329314.2900,230.0000,2.540633e+10,1.491532e+09,1.091212e+09,1.279543e+09,223825531.0,1.470606e+09,450883.212472,716736.704749,7125828096
2013,1.625059e+06,5.209852e+06,1.446902e+06,3.584792e+06,178157.5843,108597.1260,511357.3682,37471.7183,909137.8261,335816.5644,1026.0255,2.578876e+10,1.495101e+09,1.106942e+09,1.310763e+09,223737572.0,1.464392e+09,446222.795232,720612.963709,7210582016
2014,1.626226e+06,5.208838e+06,1.447809e+06,3.582609e+06,178417.2706,98812.7064,513339.7562,37811.7900,826081.8824,189475.7473,1141.8608,2.575145e+10,1.502947e+09,1.121308e+09,1.305057e+09,225030802.0,1.474566e+09,445731.976025,720677.860713,7295290880

In [9]:
new_data.to_csv('p_p_g_a_e.csv', index=True)